### ISSUE TITLE
doesn't build apk

### ISSUE THREAD

**Issue by superciccio** [YoussefKababe/admob_flutter#6]
Hi I'm trying to use your plugin but I can't get to build the apk.

below my pubspec.yaml

```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
      sdk: flutter
  chewie: ^0.8.0
  firebase_auth: ^0.6.6
  flutter_firebase_ui: ^0.0.13
  google_sign_in: ^3.2.4
  http: 0.12.0
#  firebase_admob: "^0.6.1+1"
  intl: ^0.15.7
  firebase_storage: ^1.0.4
  cloud_firestore: ^0.8.1+3
  share: "^0.5.3"
  cached_network_image: ^0.5.1
  video_player: ^0.7.2
  material_search: "^0.2.8"
  firebase_dynamic_links: ^0.1.0+1
  url_launcher: ^4.0.2
  flutter_localizations:
        sdk: 'flutter'
  fluro: ^1.3.7
  carousel_pro: "^0.0.13"
  firebase_messaging: ^2.1.0
  uni_links: "^0.1.1"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
#  admob_flutter: "^0.1.2"

dev_dependencies:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
 
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```
this is the error

> Android dependency 'com.google.android.gms:play-services-measurement-base' has different version for the compile (16.0.3) and runtime (16.0.4) classpath. You should manually set the same version via DependencyResolution

Best
